### ISSUE TITLE
const_missing: library not found

### ISSUE THREAD

**Issue by thilonel** [emartech/escher-ruby#3]
client.rb
> require 'escher'
> require 'net/http'
> 
> client = { api_key_id: 'developer', api_secret: 'MzhKUxb2vlHGfJgAMEaVIWyk5BBFilrg' }
> 
> request = {
>     method: 'GET',
>     host: 'suite.ett.local',
>     uri: 'api/v2/internal',
>     body: 'payload',
>     headers: [['Content-Type', 'application/json'], ['host', 'suite.ett.local']]
> }
> 
> escher = Escher::Auth.new('eu/suite/ems_request')
> escher.sign!(request, client)

ruby client.rb

> .rbenv/versions/2.2.0/lib/ruby/2.2.0/digest.rb:15:in `const_missing': library not found for class Digest::HMAC -- digest/hmac (LoadError)
>         from .rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/escher-0.3.2/lib/escher/auth.rb:179:in `generate_signature'
>         from .rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/escher-0.3.2/lib/escher/auth.rb:27:in `sign!'
>         from client.rb:29:in `<main>'

**Comment by thilonel** [comment]
This is related to: https://github.com/emartech/escher-ruby/issues/5

Digest::HMAC has been removed from ruby 2.2.0.
